### ISSUE TITLE
Error while building the project

### ISSUE THREAD

**Issue by anaymalpani** [HospitalRun/hospitalrun#363]
```
✓ Creating entry file 8.6 secs
(typescript) Error: D:/anaym/projects/node/f/hospitalrun/packages/components/src/components/Layout/Container.tsx(33,25): semantic error TS2769: No overload matches this call.
  Overload 1 of 2, '(props: Readonly<ReplaceProps<"symbol", BsPrefixProps<"symbol"> & ContainerProps>>): Container<"symbol">', gave the following error.
    Type '"symbol" | "object" | "a" | "abbr" | "address" | "area" | "article" | "aside" | "audio" | "b" | "base" | "bdi" | "bdo" | "big" | "blockquote" | "body" | "br" | "button" | "canvas" | ... 158 more ... | undefined' is not assignable to type '"symbol" | undefined'.
      Type '"object"' is not assignable to type '"symbol" | undefined'.
  Overload 2 of 2, '(props: ReplaceProps<"symbol", BsPrefixProps<"symbol"> & ContainerProps>, context?: any): Container<"symbol">', gave the following error.
    Type '"symbol" | "object" | "a" | "abbr" | "address" | "area" | "article" | "aside" | "audio" | "b" | "base" | "bdi" | "bdo" | "big" | "blockquote" | "body" | "br" | "button" | "canvas" | ... 158 more ... | undefined' is not assignable to type '"symbol" | undefined'.
      Type '"object"' is not assignable to type '"symbol" | undefined'.
Error: D:/anaym/projects/node/f/hospitalrun/packages/components/src/components/Layout/Container.tsx(33,25): semantic error TS2769: No overload matches this call.
  Overload 1 of 2, '(props: Readonly<ReplaceProps<"symbol", BsPrefixProps<"symbol"> & ContainerProps>>): Container<"symbol">', gave the following error.
    Type '"symbol" | "object" | "a" | "abbr" | "address" | "area" | "article" | "aside" | "audio" | "b" | "base" | "bdi" | "bdo" | "big" | "blockquote" | "body" | "br" | "button" | "canvas" | ... 158 more ... | undefined' is not assignable to type '"symbol" | undefined'.
      Type '"object"' is not assignable to type '"symbol" | undefined'.
  Overload 2 of 2, '(props: ReplaceProps<"symbol", BsPrefixProps<"symbol"> & ContainerProps>, context?: any): Container<"symbol">', gave the following error.
    Type '"symbol" | "object" | "a" | "abbr" | "address" | "area" | "article" | "aside" | "audio" | "b" | "base" | "bdi" | "bdo" | "big" | "blockquote" | "body" | "br" | "button" | "canvas" | ... 158 more ... | undefined' is not assignable to type '"symbol" | undefined'.
      Type '"object"' is not assignable to type '"symbol" | undefined'.
    at error (D:\anaym\projects\node\f\hospitalrun\packages\components\node_modules\rollup\dist\shared\node-entry.js:5400:30)
    at throwPluginError (D:\anaym\projects\node\f\hospitalrun\packages\components\node_modules\rollup\dist\shared\node-entry.js:11878:12)
    at Object.error (D:\anaym\projects\node\f\hospitalrun\packages\components\node_modules\rollup\dist\shared\node-entry.js:12912:24)
    at Object.error (D:\anaym\projects\node\f\hospitalrun\packages\components\node_modules\rollup\dist\shared\node-entry.js:12081:38)
    at RollupContext.error (D:\anaym\projects\node\f\hospitalrun\packages\components\node_modules\tsdx\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:17194:30)
    at D:\anaym\projects\node\f\hospitalrun\packages\components\node_modules\tsdx\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:24994:23
    at arrayEach (D:\anaym\projects\node\f\hospitalrun\packages\components\node_modules\tsdx\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:534:11)
    at forEach (D:\anaym\projects\node\f\hospitalrun\packages\components\node_modules\tsdx\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:9360:14)
    at printDiagnostics (D:\anaym\projects\node\f\hospitalrun\packages\components\node_modules\tsdx\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:24967:5)
    at Object.transform (D:\anaym\projects\node\f\hospitalrun\packages\components\node_modules\tsdx\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:29049:17)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @hospitalrun/components@1.8.1 build: `tsdx build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @hospitalrun/components@1.8.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\anaym\AppData\Roaming\npm-cache\_logs\2020-05-30T16_06_01_227Z-debug.log
```

## Your Environment

- _node version_: 12
- _os_: Windows

**Comment by tehKapa** [comment]
This is a yarn workspace issue when using a monorepo. It's an issue of low priority because all separate submodules build correctly. 
The team is informed of this issue but needs time to solve it. Any contributions are welcome.

**Comment by reidmeyer** [comment]
Could you clarify how to build all of the submodules to get the application to run? @tehKapa

**Comment by fox1t** [comment]
Hi! I am going to to look into this ASAP and hopefully fix the problem definitely! @reidmeyer you are right: we miss the documentation that explains how to use all the modules without mono repo. Let’s try to understand what are the main steps that are needed to use all modules in a stand alone way.

**Comment by reidmeyer** [comment]
Glad to hear @fox1t. 

My guess would be to run "yarn run build" inside each package itself, but I think that is the same thing as running yarn workspaces run build. When I do this, I get errors with components and frontend. 

That documentation would be super helpful.

**Comment by jackcmeyer** [comment]
@reidmeyer for documentation on how to contribute to the individual modules: https://github.com/HospitalRun/hospitalrun/blob/master/.github/CONTRIBUTING.md

**Comment by fox1t** [comment]
Hi! I've looked into this. The real problem is TypeScript version > 3.9.x that changed how union types work. Our dependency is listed like `"typescript": "~3.8.2"` so it wouldn't be updated to a newer minor that brakes. Do you have TS globally installed?

**Comment by reidmeyer** [comment]
@fox1t I don't think I have it installed globally, as tsc isn't recognized. Although it could have been installed by visual studio. I do have a C:\Program Files (x86)\Microsoft SDKs\TypeScript\versions\03.08.03.00, but you say it only breaks at 3.9.x.

**Comment by fox1t** [comment]
Could be a hoisting problem! Ok, lets see if my last commits fixes it! Thanks again.

**Comment by reidmeyer** [comment]
Just updating you: with the current commits, I'm getting the same errors as before. 

NPM14 throws me errors on "yarn" command:

![image](https://user-images.githubusercontent.com/16112576/84803532-bd72ee00-afc7-11ea-83f7-e09e6d057405.png)

![image](https://user-images.githubusercontent.com/16112576/84803552-c5329280-afc7-11ea-90f6-6013513c2b7f.png)

![image](https://user-images.githubusercontent.com/16112576/84803585-cebbfa80-afc7-11ea-9b94-8f071a713874.png)


NPM12 gets passed the yarn command, but then on workspaces build it similarly fails with the overload:

![image](https://user-images.githubusercontent.com/16112576/84804577-9bc63680-afc8-11ea-90fc-489962e7485f.png)

**Comment by mraqkhan** [comment]
I am facing the same issue. Did someone get it working? How to fix this?

**Comment by tehKapa** [comment]
We are looking into a new solution for the management of the monorepo... we don't have an ETA

**Comment by Razi321** [comment]
i'm still getting this error , anyone solved it ?

**Comment by tehKapa** [comment]
Unfortunately, yes. It is not easy to find a tool for the management of this complicated software

**Comment by Razi321** [comment]
so how can I R run this project on my local machine ? i've tried what's available but nothing works

**Comment by tehKapa** [comment]
You have to run hospitalrun-server and hospitalrun-frontend separately
